platform :ios, '9.0'

target 'OCDemo' do
  # use_frameworks!
  
  pod 'AFNetworking', "~> 3.2.1"
  pod 'SDWebImage', "~> 4.4.3"
  pod 'Masonry', "~> 1.1.0"
  pod 'MJRefresh', "~> 3.1.15"
  pod 'FMDB', "~> 2.7.5"
  pod 'MBProgressHUD', "~> 1.1.0"
  pod 'TZImagePickerController', "~> 3.1.9"
  pod 'SDCycleScrollView', "~> 1.75"
  pod 'pop', "~> 1.0.12"
  pod 'ReactiveObjC', "~> 3.1.0"
  
end
